apiVersion: v1
kind: Pod
metadata:
  name: cic-vpx
  namespace: vpx-ingress
  labels:
    app: cic-vpx
spec:
      serviceAccountName: cpx
      containers:
      - name: cic-vpx
        image: "quay.io/citrix/citrix-k8s-ingress-controller:1.10.2.1"
        env:
         # Set NetScaler NSIP/SNIP, SNIP in case of HA (mgmt has to be enabled)
         - name: "NS_IP"
           value: "x.x.x.x"
         # Set username for Nitro
         # Set log level
         - name: "NS_ENABLE_MONITORING"
           value: "YES"
         - name: "NS_USER"
           value: "demo"
         - name: "NS_PASSWORD"
           value: "demo"
         - name: "EULA"
           value: "yes"
         - name: "LOGLEVEL"
           value: "DEBUG"
        args:
          - --default-ssl-certificate
            monitoring/dashboards-secret
          - --ingress-classes
            vpx
          - --feature-node-watch
            true
        imagePullPolicy: IfNotPresent

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend-ingress
  namespace: vpx-ingress
  annotations:
  # /* The CS virtual server is derived from the combination of insecure-port/s>
   ingress.citrix.com/frontend-ip: x.x.x.x
   ingress.citrix.com/insecure-port: "80"
   ingress.citrix.com/secure-port: "443"
   ingress.citrix.com/frontend-httpprofile: '{"dropinvalreqs" : "enabled", "websocket" : "enabled"}'
   ingress.citrix.com/insecure-termination: "redirect"
   kubernetes.io/ingress.class: "vpx"
spec:
  rules:
  - host:

---

# add exporter for metrics
apiVersion: apps/v1
kind: Deployment
metadata:
  name: exporter
  namespace: vpx-ingress
spec:
  selector:
    matchLabels:
      app: exporter
  replicas: 1
  template:
    metadata:
      labels:
        app: exporter
    spec:
      containers:
        - name: exporter
          image: "quay.io/citrix/citrix-adc-metrics-exporter:1.3"
          args:
            - "--target-nsip=x.x.x.x"
            - "--port=8888"
          env:
          - name: "NS_USER"
            value: "xx"
          - name: "NS_PASSWORD"
            value: "xx"
          imagePullPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: exporter-vpx
  namespace: vpx-ingress
  labels:
    app: exporter
    service-type: citrix-adc-monitor
spec:
  type: ClusterIP
  ports:
  - port: 8888
    targetPort: 8888
    name: exporter-port
