apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: xoa
  annotations:
    kompose.cmd: kompose convert -f xoa-compose.yml
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    app: orchestra
  name: orchestra
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orchestra
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f xoa-compose.yml
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        app: orchestra
    spec:
      containers:
      - env:
        - name: DEBUG
          value: xo:main
        - name: NODE_ENV
          value: production
        - name: XOA_PLAN
          value: "5"
        image: ezka77/xen-orchestra-ce
        imagePullPolicy: ""
        name: xo-server
        ports:
        - containerPort: 8000
        resources: {}
        volumeMounts:
        - mountPath: /storage
          name: orchestra-claim0
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: orchestra-claim0
        persistentVolumeClaim:
          claimName: orchestra-claim0
status: {}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: xoa
  creationTimestamp: null
  labels:
    io.kompose.service: orchestra-claim0
  name: orchestra-claim0
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
