{
 "title": "Ingress service stats",
 "time": { "from": "2019-10-10T09:40:38.332Z", "to": "2019-10-10T10:10:38.332Z" },
 "templating": {
  "list": [
   { "name": "datasource_prometheus", "label": "datasource_prometheus", "query": "prometheus" },
   {
    "name": "Ingress",
    "label": "Ingress",
    "query": "label_values(citrixadc_k8s_ing_lb_ingress_name)"
   },
   {
    "name": "Service",
    "label": "Service",
    "query": "label_values({citrixadc_k8s_ing_lb_ingress_name=~\"$Ingress\"}, citrixadc_k8s_ing_lb_service_name)"
   }
  ]
 },
 "panels": [
  {
   "title": "service requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "citrixadc_k8s_ing_lb_hits_total {citrixadc_k8s_ing_lb_service_name=~\"$Service\"}"
    }
   ]
  },
  {
   "title": "surge queue",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "citrixadc_k8s_ing_lb_surge_queue_requests_count {citrixadc_k8s_ing_lb_service_name=~\"$Service\"}"
    }
   ]
  },
  {
   "title": "RPS",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "citrixadc_k8s_ing_lb_request_rate {citrixadc_k8s_ing_lb_service_name=~\"$Service\"}"
    }
   ]
  },
  {
   "title": "Invalid Request/Response",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "citrixadc_k8s_ing_lb_invalid_response_request_total {citrixadc_k8s_ing_lb_service_name=~\"$Service\"}"
    }
   ]
  }
 ]
}