{
 "title": "System Stats",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource_prometheus", "label": "datasource_prometheus", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Licensed Throughput rate ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "((citrixadc_througput_rx_mbits_rate*0.001)/citrixadc_allocated_licensed_bandwidth_total)*100"
    }
   ]
  },
  {
   "title": "Memory Utilization Percentage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "citrixadc_memory_usage_percent" }
   ]
  },
  {
   "title": "CPU Utilization Percentage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "citrixadc_packet_cpu_usage_percent"
    }
   ]
  }
 ]
}